### ISSUE TITLE
MIT License 

### ISSUE THREAD

**Issue by do-not-commit** [ccbrown/iocraft#24]
There are empty placeholders where copyright information is supposed to be

Also, lib looks nice! Good luck with the project

**Comment by ccbrown** [comment]
Thanks for letting me know! This is now fixed in main.

I decided to go the route that seems like it might be the most common in the Rust community: Just delete that line entirely, à la...

https://github.com/rust-lang/rust/blob/master/LICENSE-MIT
https://github.com/bevyengine/bevy/blob/main/LICENSE-MIT
https://github.com/dtolnay/indoc/blob/master/LICENSE-MIT
